-- MySQL Script generated by MySQL Workbench
-- Tue Dec 11 18:59:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Mutuelle
-- -----------------------------------------------------
-- MCD de gesiton de la mutuelle des enseignants de l'ENSP

-- -----------------------------------------------------
-- Schema Mutuelle
--
-- MCD de gesiton de la mutuelle des enseignants de l'ENSP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mutuelle` DEFAULT CHARACTER SET utf8 ;
USE `Mutuelle` ;

-- -----------------------------------------------------
-- Table `Mutuelle`.`Enseignant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mutuelle`.`Enseignant` (
  `idenseignant` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NULL,
  `date_inscription` DATETIME NOT NULL,
  `inscrit` TINYINT NULL DEFAULT 0,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idenseignant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mutuelle`.`Contribution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mutuelle`.`Contribution` (
  `idcontribution` INT NOT NULL,
  `montant` DECIMAL(10,2) NULL,
  `session` VARCHAR(45) NULL,
  `Enseignant_idenseignant` INT NOT NULL,
  PRIMARY KEY (`idcontribution`),
  INDEX `fk_Contribution_Enseignant_idx` (`Enseignant_idenseignant` ASC),
  CONSTRAINT `fk_Contribution_Enseignant`
    FOREIGN KEY (`Enseignant_idenseignant`)
    REFERENCES `Mutuelle`.`Enseignant` (`idenseignant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mutuelle`.`Caisse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mutuelle`.`Caisse` (
  `montant` INT NULL,
  `typeCaisse` VARCHAR(45) NULL,
  `Contribution_idcontribution` INT NOT NULL,
  PRIMARY KEY (`Contribution_idcontribution`),
  CONSTRAINT `fk_Caisse_Contribution1`
    FOREIGN KEY (`Contribution_idcontribution`)
    REFERENCES `Mutuelle`.`Contribution` (`idcontribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mutuelle`.`Emprunt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mutuelle`.`Emprunt` (
  `idEmprunt` INT NOT NULL,
  `montant` DECIMAL(10,2) NOT NULL,
  `session` DATETIME NOT NULL,
  `interet` DECIMAL(2,2) NULL,
  `dateButoir` DATETIME NULL,
  `somme` DECIMAL(10,2) NULL,
  `Enseignant_idenseignant` INT NOT NULL,
  PRIMARY KEY (`idEmprunt`, `Enseignant_idenseignant`),
  INDEX `fk_Emprunt_Enseignant1_idx` (`Enseignant_idenseignant` ASC),
  CONSTRAINT `fk_Emprunt_Enseignant1`
    FOREIGN KEY (`Enseignant_idenseignant`)
    REFERENCES `Mutuelle`.`Enseignant` (`idenseignant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mutuelle`.`Remboursement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mutuelle`.`Remboursement` (
  `idRemboursement` INT NOT NULL,
  `session` DATETIME NULL,
  `montant` DECIMAL(10,2) NULL,
  `reste` DECIMAL(10,2) NULL,
  `Emprunt_idEmprunt` INT NOT NULL,
  `Emprunt_Enseignant_idenseignant` INT NOT NULL,
  PRIMARY KEY (`idRemboursement`, `Emprunt_idEmprunt`, `Emprunt_Enseignant_idenseignant`),
  INDEX `fk_Remboursement_Emprunt1_idx` (`Emprunt_idEmprunt` ASC, `Emprunt_Enseignant_idenseignant` ASC),
  CONSTRAINT `fk_Remboursement_Emprunt1`
    FOREIGN KEY (`Emprunt_idEmprunt` , `Emprunt_Enseignant_idenseignant`)
    REFERENCES `Mutuelle`.`Emprunt` (`idEmprunt` , `Enseignant_idenseignant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
